id <- c(1:10)
name <- c("John Mendes", "Rob Stewart", "Rachel Abrahamson", "Christy Hickman", "Johnson Harper", "Candace Miller", "Carlson Landy", "Pansy Jordan", "Darius Berry", "Claudia Garcia")
job_title <- c("Professional", "Programmer", "Management", "Clerical", "Developer", "Programmer", "Management", "Clerical", "Developer", "Programmer")
employee <- data.frame(id, name, job_title)
head(employee)
print(employee)
separate(employee, name, into = c("first_name", "last_name"),sep = " ")

first_name <- c("jobs", "lulu", "easy")
last_name <- c("aww", "ha", "emm")
job_title <-c("ya", "gun", "hehe")
employee <- data.frame(first_name, last_name, job_title)
unite(employee, "name", c("first_name", "last_name"), sep = " ")
print(employee)
